[2025-09-21T23:21:20.264+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-09-21T23:21:20.314+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nawy_real_estate_pipeline.installing_required_dependencies manual__2025-09-20T05:27:01.289552+00:00 [queued]>
[2025-09-21T23:21:20.331+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nawy_real_estate_pipeline.installing_required_dependencies manual__2025-09-20T05:27:01.289552+00:00 [queued]>
[2025-09-21T23:21:20.333+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-09-21T23:21:20.395+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): installing_required_dependencies> on 2025-09-20 05:27:01.289552+00:00
[2025-09-21T23:21:20.407+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=285) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-09-21T23:21:20.413+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'nawy_real_estate_pipeline', 'installing_required_dependencies', 'manual__2025-09-20T05:27:01.289552+00:00', '--job-id', '362', '--raw', '--subdir', 'DAGS_FOLDER/nawy_dag.py', '--cfg-path', '/tmp/tmpvbzxrzyz']
[2025-09-21T23:21:20.418+0000] {standard_task_runner.py:72} INFO - Started process 313 to run task
[2025-09-21T23:21:20.420+0000] {standard_task_runner.py:105} INFO - Job 362: Subtask installing_required_dependencies
[2025-09-21T23:21:20.571+0000] {task_command.py:467} INFO - Running <TaskInstance: nawy_real_estate_pipeline.installing_required_dependencies manual__2025-09-20T05:27:01.289552+00:00 [running]> on host b65782a7021d
[2025-09-21T23:21:21.009+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='nawy_real_estate_pipeline' AIRFLOW_CTX_TASK_ID='installing_required_dependencies' AIRFLOW_CTX_EXECUTION_DATE='2025-09-20T05:27:01.289552+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-20T05:27:01.289552+00:00'
[2025-09-21T23:21:21.013+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-09-21T23:21:21.014+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-09-21T23:21:21.019+0000] {logging_mixin.py:190} INFO - Current task name:installing_required_dependencies state:running start_date:2025-09-21 23:21:20.315703+00:00
[2025-09-21T23:21:21.020+0000] {logging_mixin.py:190} INFO - Dag name:nawy_real_estate_pipeline and current dag run status:running
[2025-09-21T23:21:21.023+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-09-21T23:21:21.027+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-09-21T23:21:21.041+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', ' cd /opt/***/dags/../include/nawy_dbt_project && dbt clean &&  dbt deps --no-version-check ']
[2025-09-21T23:21:21.071+0000] {subprocess.py:99} INFO - Output:
[2025-09-21T23:21:31.380+0000] {subprocess.py:106} INFO - [0m23:21:31  Running with dbt=1.10.11
[2025-09-21T23:21:32.216+0000] {subprocess.py:106} INFO - [0m23:21:32  Checking /opt/***/include/nawy_dbt_project/target/*
[2025-09-21T23:21:32.235+0000] {subprocess.py:106} INFO - [0m23:21:32  Cleaned /opt/***/include/nawy_dbt_project/target/*
[2025-09-21T23:21:32.236+0000] {subprocess.py:106} INFO - [0m23:21:32  Checking /opt/***/include/nawy_dbt_project/dbt_packages/*
[2025-09-21T23:21:32.237+0000] {subprocess.py:106} INFO - [0m23:21:32  Cleaned /opt/***/include/nawy_dbt_project/dbt_packages/*
[2025-09-21T23:21:32.238+0000] {subprocess.py:106} INFO - [0m23:21:32  Finished cleaning all paths.
[2025-09-21T23:21:44.886+0000] {subprocess.py:106} INFO - [0m23:21:44  Running with dbt=1.10.11
[2025-09-21T23:21:45.847+0000] {subprocess.py:106} INFO - [0m23:21:45  Installing dbt-labs/dbt_utils
[2025-09-21T23:21:56.605+0000] {subprocess.py:106} INFO - [0m23:21:56  Encountered an error:
[2025-09-21T23:21:56.608+0000] {subprocess.py:106} INFO - [('dbt_packages/dbt-utils-1.3.0/.github', 'dbt_packages/dbt_utils/.github', "[Errno 17] File exists: 'dbt_packages/dbt_utils/.github'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/data/sql/data_events_20180103.csv', 'dbt_packages/dbt_utils/integration_tests/data/sql/data_events_20180103.csv', "[Errno 2] No such file or directory: 'dbt_packages/dbt_utils/integration_tests/data/sql/data_events_20180103.csv'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/data/sql/data_filtered_columns_in_relation.csv', 'dbt_packages/dbt_utils/integration_tests/data/sql/data_filtered_columns_in_relation.csv', "[Errno 2] No such file or directory: 'dbt_packages/dbt_utils/integration_tests/data/sql/data_filtered_columns_in_relation.csv'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/data/sql/data_filtered_columns_in_relation_expected.csv', 'dbt_packages/dbt_utils/integration_tests/data/sql/data_filtered_columns_in_relation_expected.csv', "[Errno 2] No such file or directory: 'dbt_packages/dbt_utils/integration_tests/data/sql/data_filtered_columns_in_relation_expected.csv'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/data/sql/data_generate_series.csv', 'dbt_packages/dbt_utils/integration_tests/data/sql/data_generate_series.csv', "[Errno 2] No such file or directory: 'dbt_packages/dbt_utils/integration_tests/data/sql/data_generate_series.csv'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/data/sql/data_generate_surrogate_key.csv', 'dbt_packages/dbt_utils/integration_tests/data/sql/data_generate_surrogate_key.csv', "[Errno 2] No such file or directory: 'dbt_packages/dbt_utils/integration_tests/data/sql/data_generate_surrogate_key.csv'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/data/sql/data_get_column_values.csv', 'dbt_packages/dbt_utils/integration_tests/data/sql/data_get_column_values.csv', "[Errno 2] No such file or directory: 'dbt_packages/dbt_utils/integration_tests/data/sql/data_get_column_values.csv'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/data/sql/data_get_column_values_dropped.csv', 'dbt_packages/dbt_utils/integration_tests/data/sql/data_get_column_values_dropped.csv', "[Errno 2] No such file or directory: 'dbt_packages/dbt_utils/integration_tests/data/sql/data_get_column_values_dropped.csv'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/data/sql/data_get_column_values_where.csv', 'dbt_packages/dbt_utils/integration_tests/data/sql/data_get_column_values_where.csv', "[Errno 2] No such file or directory: 'dbt_packages/dbt_utils/integration_tests/data/sql/data_get_column_values_where.csv'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/data/sql/data_get_column_values_where_expected.csv', 'dbt_packages/dbt_utils/integration_tests/data/sql/data_get_column_values_where_expected.csv', "[Errno 2] No such file or directory: 'dbt_packages/dbt_utils/integration_tests/data/sql/data_get_column_values_where_expected.csv'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/data/sql/data_get_query_results_as_dict.csv', 'dbt_packages/dbt_utils/integration_tests/data/sql/data_get_query_results_as_dict.csv', "[Errno 2] No such file or directory: 'dbt_packages/dbt_utils/integration_tests/data/sql/data_get_query_results_as_dict.csv'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/data/sql/data_get_single_value.csv', 'dbt_packages/dbt_utils/integration_tests/data/sql/data_get_single_value.csv', "[Errno 2] No such file or directory: 'dbt_packages/dbt_utils/integration_tests/data/sql/data_get_single_value.csv'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/data/sql/data_nullcheck_table.csv', 'dbt_packages/dbt_utils/integration_tests/data/sql/data_nullcheck_table.csv', "[Errno 2] No such file or directory: 'dbt_packages/dbt_utils/integration_tests/data/sql/data_nullcheck_table.csv'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/data/sql/data_pivot.csv', 'dbt_packages/dbt_utils/integration_tests/data/sql/data_pivot.csv', "[Errno 2] No such file or directory: 'dbt_packages/dbt_utils/integration_tests/data/sql/data_pivot.csv'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/data/sql/data_pivot_expected.csv', 'dbt_packages/dbt_utils/integration_tests/data/sql/data_pivot_expected.csv', "[Errno 2] No such file or directory: 'dbt_packages/dbt_utils/integration_tests/data/sql/data_pivot_expected.csv'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/data/sql/data_pivot_expected_apostrophe.csv', 'dbt_packages/dbt_utils/integration_tests/data/sql/data_pivot_expected_apostrophe.csv', "[Errno 2] No such file or directory: 'dbt_packages/dbt_utils/integration_tests/data/sql/data_pivot_expected_apostrophe.csv'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/data/sql/data_safe_add.csv', 'dbt_packages/dbt_utils/integration_tests/data/sql/data_safe_add.csv', "[Errno 2] No such file or directory: 'dbt_packages/dbt_utils/integration_tests/data/sql/data_safe_add.csv'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/data/sql/data_safe_divide.csv', 'dbt_packages/dbt_utils/integration_tests/data/sql/data_safe_divide.csv', "[Errno 2] No such file or directory: 'dbt_packages/dbt_utils/integration_tests/data/sql/data_safe_divide.csv'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/data/sql/data_safe_divide_denominator_expressions.csv', 'dbt_packages/dbt_utils/integration_tests/data/sql/data_safe_divide_denominator_expressions.csv', "[Errno 2] No such file or directory: 'dbt_packages/dbt_utils/integration_tests/data/sql/data_safe_divide_denominator_expressions.csv'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/data/sql/data_safe_divide_numerator_expressions.csv', 'dbt_packages/dbt_utils/integration_tests/data/sql/data_safe_divide_numerator_expressions.csv', "[Errno 2] No such file or directory: 'dbt_packages/dbt_utils/integration_tests/data/sql/data_safe_divide_numerator_expressions.csv'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/data/sql/data_safe_subtract.csv', 'dbt_packages/dbt_utils/integration_tests/data/sql/data_safe_subtract.csv', "[Errno 2] No such file or directory: 'dbt_packages/dbt_utils/integration_tests/data/sql/data_safe_subtract.csv'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/data/sql/data_star.csv', 'dbt_packages/dbt_utils/integration_tests/data/sql/data_star.csv', "[Errno 2] No such file or directory: 'dbt_packages/dbt_utils/integration_tests/data/sql/data_star.csv'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/data/sql/data_star_aggregate.csv', 'dbt_packages/dbt_utils/integration_tests/data/sql/data_star_aggregate.csv', "[Errno 2] No such file or directory: 'dbt_packages/dbt_utils/integration_tests/data/sql/data_star_aggregate.csv'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/data/sql/data_star_aggregate_expected.csv', 'dbt_packages/dbt_utils/integration_tests/data/sql/data_star_aggregate_expected.csv', "[Errno 2] No such file or directory: 'dbt_packages/dbt_utils/integration_tests/data/sql/data_star_aggregate_expected.csv'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/data/sql/data_star_expected.csv', 'dbt_packages/dbt_utils/integration_tests/data/sql/data_star_expected.csv', "[Errno 2] No such file or directory: 'dbt_packages/dbt_utils/integration_tests/data/sql/data_star_expected.csv'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/data/sql/data_star_prefix_suffix_expected.csv', 'dbt_packages/dbt_utils/integration_tests/data/sql/data_star_prefix_suffix_expected.csv', "[Errno 2] No such file or directory: 'dbt_packages/dbt_utils/integration_tests/data/sql/data_star_prefix_suffix_expected.csv'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/data/sql/data_star_quote_identifiers.csv', 'dbt_packages/dbt_utils/integration_tests/data/sql/data_star_quote_identifiers.csv', "[Errno 2] No such file or directory: 'dbt_packages/dbt_utils/integration_tests/data/sql/data_star_quote_identifiers.csv'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/data/sql/data_union_events_expected.csv', 'dbt_packages/dbt_utils/integration_tests/data/sql/data_union_events_expected.csv', "[Errno 2] No such file or directory: 'dbt_packages/dbt_utils/integration_tests/data/sql/data_union_events_expected.csv'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/data/sql/data_union_exclude_expected.csv', 'dbt_packages/dbt_utils/integration_tests/data/sql/data_union_exclude_expected.csv', "[Errno 2] No such file or directory: 'dbt_packages/dbt_utils/integration_tests/data/sql/data_union_exclude_expected.csv'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/data/sql/data_union_expected.csv', 'dbt_packages/dbt_utils/integration_tests/data/sql/data_union_expected.csv', "[Errno 2] No such file or directory: 'dbt_packages/dbt_utils/integration_tests/data/sql/data_union_expected.csv'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/data/sql/data_union_table_1.csv', 'dbt_packages/dbt_utils/integration_tests/data/sql/data_union_table_1.csv', "[Errno 2] No such file or directory: 'dbt_packages/dbt_utils/integration_tests/data/sql/data_union_table_1.csv'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/data/sql/data_union_table_2.csv', 'dbt_packages/dbt_utils/integration_tests/data/sql/data_union_table_2.csv', "[Errno 2] No such file or directory: 'dbt_packages/dbt_utils/integration_tests/data/sql/data_union_table_2.csv'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/data/sql/data_unpivot.csv', 'dbt_packages/dbt_utils/integration_tests/data/sql/data_unpivot.csv', "[Errno 2] No such file or directory: 'dbt_packages/dbt_utils/integration_tests/data/sql/data_unpivot.csv'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/data/sql/data_unpivot_bool.csv', 'dbt_packages/dbt_utils/integration_tests/data/sql/data_unpivot_bool.csv', "[Errno 2] No such file or directory: 'dbt_packages/dbt_utils/integration_tests/data/sql/data_unpivot_bool.csv'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/data/sql/data_unpivot_bool_expected.csv', 'dbt_packages/dbt_utils/integration_tests/data/sql/data_unpivot_bool_expected.csv', "[Errno 2] No such file or directory: 'dbt_packages/dbt_utils/integration_tests/data/sql/data_unpivot_bool_expected.csv'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/data/sql/data_unpivot_expected.csv', 'dbt_packages/dbt_utils/integration_tests/data/sql/data_unpivot_expected.csv', "[Errno 2] No such file or directory: 'dbt_packages/dbt_utils/integration_tests/data/sql/data_unpivot_expected.csv'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/data/sql/data_unpivot_original_api_expected.csv', 'dbt_packages/dbt_utils/integration_tests/data/sql/data_unpivot_original_api_expected.csv', "[Errno 2] No such file or directory: 'dbt_packages/dbt_utils/integration_tests/data/sql/data_unpivot_original_api_expected.csv'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/data/sql/data_unpivot_quote.csv', 'dbt_packages/dbt_utils/integration_tests/data/sql/data_unpivot_quote.csv', "[Errno 2] No such file or directory: 'dbt_packages/dbt_utils/integration_tests/data/sql/data_unpivot_quote.csv'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/data/sql/data_unpivot_quote_expected.csv', 'dbt_packages/dbt_utils/integration_tests/data/sql/data_unpivot_quote_expected.csv', "[Errno 2] No such file or directory: 'dbt_packages/dbt_utils/integration_tests/data/sql/data_unpivot_quote_expected.csv'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/data/sql/data_width_bucket.csv', 'dbt_packages/dbt_utils/integration_tests/data/sql/data_width_bucket.csv', "[Errno 2] No such file or directory: 'dbt_packages/dbt_utils/integration_tests/data/sql/data_width_bucket.csv'"), (<DirEntry 'sql'>, 'dbt_packages/dbt_utils/integration_tests/data/sql', '[Errno 2] No such file or directory'), ('dbt_packages/dbt-utils-1.3.0/integration_tests/data/web/data_urls.csv', 'dbt_packages/dbt_utils/integration_tests/data/web/data_urls.csv', "[Errno 2] No such file or directory: 'dbt_packages/dbt-utils-1.3.0/integration_tests/data/web/data_urls.csv'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/data/web/data_url_host.csv', 'dbt_packages/dbt_utils/integration_tests/data/web/data_url_host.csv', "[Errno 2] No such file or directory: 'dbt_packages/dbt-utils-1.3.0/integration_tests/data/web/data_url_host.csv'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/data/web/data_url_path.csv', 'dbt_packages/dbt_utils/integration_tests/data/web/data_url_path.csv', "[Errno 2] No such file or directory: 'dbt_packages/dbt-utils-1.3.0/integration_tests/data/web/data_url_path.csv'"), (<DirEntry 'web'>, 'dbt_packages/dbt_utils/integration_tests/data/web', "[Errno 2] No such file or directory: 'dbt_packages/dbt-utils-1.3.0/integration_tests/data/web'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/dbt_project.yml', 'dbt_packages/dbt_utils/integration_tests/dbt_project.yml', "[Errno 2] No such file or directory: 'dbt_packages/dbt-utils-1.3.0/integration_tests/dbt_project.yml'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/macros', 'dbt_packages/dbt_utils/integration_tests/macros', "[Errno 2] No such file or directory: 'dbt_packages/dbt-utils-1.3.0/integration_tests/macros'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/models', 'dbt_packages/dbt_utils/integration_tests/models', "[Errno 2] No such file or directory: 'dbt_packages/dbt-utils-1.3.0/integration_tests/models'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/package-lock.yml', 'dbt_packages/dbt_utils/integration_tests/package-lock.yml', "[Errno 2] No such file or directory: 'dbt_packages/dbt-utils-1.3.0/integration_tests/package-lock.yml'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/packages.yml', 'dbt_packages/dbt_utils/integration_tests/packages.yml', "[Errno 2] No such file or directory: 'dbt_packages/dbt-utils-1.3.0/integration_tests/packages.yml'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/profiles.yml', 'dbt_packages/dbt_utils/integration_tests/profiles.yml', "[Errno 2] No such file or directory: 'dbt_packages/dbt-utils-1.3.0/integration_tests/profiles.yml'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/README.md', 'dbt_packages/dbt_utils/integration_tests/README.md', "[Errno 2] No such file or directory: 'dbt_packages/dbt-utils-1.3.0/integration_tests/README.md'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/tests', 'dbt_packages/dbt_utils/integration_tests/tests', "[Errno 2] No such file or directory: 'dbt_packages/dbt-utils-1.3.0/integration_tests/tests'"), ('dbt_packages/dbt-utils-1.3.0/LICENSE', 'dbt_packages/dbt_utils/LICENSE', "[Errno 2] No such file or directory: 'dbt_packages/dbt-utils-1.3.0/LICENSE'"), ('dbt_packages/dbt-utils-1.3.0/macros', 'dbt_packages/dbt_utils/macros', "[Errno 2] No such file or directory: 'dbt_packages/dbt-utils-1.3.0/macros'"), ('dbt_packages/dbt-utils-1.3.0/Makefile', 'dbt_packages/dbt_utils/Makefile', "[Errno 2] No such file or directory: 'dbt_packages/dbt-utils-1.3.0/Makefile'"), ('dbt_packages/dbt-utils-1.3.0/pytest.ini', 'dbt_packages/dbt_utils/pytest.ini', "[Errno 2] No such file or directory: 'dbt_packages/dbt-utils-1.3.0/pytest.ini'"), ('dbt_packages/dbt-utils-1.3.0/README.md', 'dbt_packages/dbt_utils/README.md', "[Errno 2] No such file or directory: 'dbt_packages/dbt-utils-1.3.0/README.md'"), ('dbt_packages/dbt-utils-1.3.0/RELEASE.md', 'dbt_packages/dbt_utils/RELEASE.md', "[Errno 2] No such file or directory: 'dbt_packages/dbt-utils-1.3.0/RELEASE.md'"), ('dbt_packages/dbt-utils-1.3.0/run_functional_test.sh', 'dbt_packages/dbt_utils/run_functional_test.sh', "[Errno 2] No such file or directory: 'dbt_packages/dbt-utils-1.3.0/run_functional_test.sh'"), ('dbt_packages/dbt-utils-1.3.0/run_test.sh', 'dbt_packages/dbt_utils/run_test.sh', "[Errno 2] No such file or directory: 'dbt_packages/dbt-utils-1.3.0/run_test.sh'"), ('dbt_packages/dbt-utils-1.3.0/supported_adapters.env', 'dbt_packages/dbt_utils/supported_adapters.env', "[Errno 2] No such file or directory: 'dbt_packages/dbt-utils-1.3.0/supported_adapters.env'"), ('dbt_packages/dbt-utils-1.3.0/tox.ini', 'dbt_packages/dbt_utils/tox.ini', "[Errno 2] No such file or directory: 'dbt_packages/dbt-utils-1.3.0/tox.ini'")]
[2025-09-21T23:21:56.625+0000] {subprocess.py:106} INFO - [0m23:21:56  Traceback (most recent call last):
[2025-09-21T23:21:56.627+0000] {subprocess.py:106} INFO -   File "/usr/local/lib/python3.12/shutil.py", line 847, in move
[2025-09-21T23:21:56.628+0000] {subprocess.py:106} INFO -     os.rename(src, real_dst)
[2025-09-21T23:21:56.629+0000] {subprocess.py:106} INFO - PermissionError: [Errno 13] Permission denied: 'dbt_packages/dbt-utils-1.3.0' -> 'dbt_packages/dbt_utils'
[2025-09-21T23:21:56.630+0000] {subprocess.py:106} INFO - 
[2025-09-21T23:21:56.631+0000] {subprocess.py:106} INFO - During handling of the above exception, another exception occurred:
[2025-09-21T23:21:56.631+0000] {subprocess.py:106} INFO - 
[2025-09-21T23:21:56.632+0000] {subprocess.py:106} INFO - Traceback (most recent call last):
[2025-09-21T23:21:56.633+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/dbt/cli/requires.py", line 178, in wrapper
[2025-09-21T23:21:56.634+0000] {subprocess.py:106} INFO -     result, success = func(*args, **kwargs)
[2025-09-21T23:21:56.636+0000] {subprocess.py:106} INFO -                       ^^^^^^^^^^^^^^^^^^^^^
[2025-09-21T23:21:56.641+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/dbt/cli/requires.py", line 128, in wrapper
[2025-09-21T23:21:56.645+0000] {subprocess.py:106} INFO -     return func(*args, **kwargs)
[2025-09-21T23:21:56.656+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^
[2025-09-21T23:21:56.661+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/dbt/cli/requires.py", line 254, in wrapper
[2025-09-21T23:21:56.662+0000] {subprocess.py:106} INFO -     return func(*args, **kwargs)
[2025-09-21T23:21:56.662+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^
[2025-09-21T23:21:56.664+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/dbt/cli/requires.py", line 303, in wrapper
[2025-09-21T23:21:56.664+0000] {subprocess.py:106} INFO -     return func(*args, **kwargs)
[2025-09-21T23:21:56.665+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^
[2025-09-21T23:21:56.666+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/dbt/cli/main.py", line 461, in deps
[2025-09-21T23:21:56.667+0000] {subprocess.py:106} INFO -     results = task.run()
[2025-09-21T23:21:56.668+0000] {subprocess.py:106} INFO -               ^^^^^^^^^^
[2025-09-21T23:21:56.669+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/dbt/task/deps.py", line 258, in run
[2025-09-21T23:21:56.670+0000] {subprocess.py:106} INFO -     package.install(self.project, renderer)
[2025-09-21T23:21:56.671+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/dbt/deps/registry.py", line 63, in install
[2025-09-21T23:21:56.672+0000] {subprocess.py:106} INFO -     self._install(project, renderer)
[2025-09-21T23:21:56.673+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/dbt/deps/base.py", line 121, in _install
[2025-09-21T23:21:56.674+0000] {subprocess.py:106} INFO -     connection_exception_retry(download_untar_fn, 5)
[2025-09-21T23:21:56.676+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/dbt_common/utils/connection.py", line 22, in connection_exception_retry
[2025-09-21T23:21:56.680+0000] {subprocess.py:106} INFO -     return fn()
[2025-09-21T23:21:56.685+0000] {subprocess.py:106} INFO -            ^^^^
[2025-09-21T23:21:56.686+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/dbt/deps/base.py", line 133, in download_and_untar
[2025-09-21T23:21:56.687+0000] {subprocess.py:106} INFO -     system.untar_package(tar_path, deps_path, package_name)
[2025-09-21T23:21:56.688+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/dbt_common/clients/system.py", line 649, in untar_package
[2025-09-21T23:21:56.690+0000] {subprocess.py:106} INFO -     dbt_common.clients.system.rename(downloaded_path, desired_path, force=True)
[2025-09-21T23:21:56.695+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/dbt_common/clients/system.py", line 612, in rename
[2025-09-21T23:21:56.697+0000] {subprocess.py:106} INFO -     shutil.move(from_path, to_path)
[2025-09-21T23:21:56.698+0000] {subprocess.py:106} INFO -   File "/usr/local/lib/python3.12/shutil.py", line 863, in move
[2025-09-21T23:21:56.699+0000] {subprocess.py:106} INFO -     copytree(src, real_dst, copy_function=copy_function,
[2025-09-21T23:21:56.701+0000] {subprocess.py:106} INFO -   File "/usr/local/lib/python3.12/shutil.py", line 600, in copytree
[2025-09-21T23:21:56.711+0000] {subprocess.py:106} INFO -     return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
[2025-09-21T23:21:56.712+0000] {subprocess.py:106} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-09-21T23:21:56.713+0000] {subprocess.py:106} INFO -   File "/usr/local/lib/python3.12/shutil.py", line 554, in _copytree
[2025-09-21T23:21:56.714+0000] {subprocess.py:106} INFO -     raise Error(errors)
[2025-09-21T23:21:56.715+0000] {subprocess.py:106} INFO - shutil.Error: [('dbt_packages/dbt-utils-1.3.0/.github', 'dbt_packages/dbt_utils/.github', "[Errno 17] File exists: 'dbt_packages/dbt_utils/.github'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/data/sql/data_events_20180103.csv', 'dbt_packages/dbt_utils/integration_tests/data/sql/data_events_20180103.csv', "[Errno 2] No such file or directory: 'dbt_packages/dbt_utils/integration_tests/data/sql/data_events_20180103.csv'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/data/sql/data_filtered_columns_in_relation.csv', 'dbt_packages/dbt_utils/integration_tests/data/sql/data_filtered_columns_in_relation.csv', "[Errno 2] No such file or directory: 'dbt_packages/dbt_utils/integration_tests/data/sql/data_filtered_columns_in_relation.csv'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/data/sql/data_filtered_columns_in_relation_expected.csv', 'dbt_packages/dbt_utils/integration_tests/data/sql/data_filtered_columns_in_relation_expected.csv', "[Errno 2] No such file or directory: 'dbt_packages/dbt_utils/integration_tests/data/sql/data_filtered_columns_in_relation_expected.csv'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/data/sql/data_generate_series.csv', 'dbt_packages/dbt_utils/integration_tests/data/sql/data_generate_series.csv', "[Errno 2] No such file or directory: 'dbt_packages/dbt_utils/integration_tests/data/sql/data_generate_series.csv'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/data/sql/data_generate_surrogate_key.csv', 'dbt_packages/dbt_utils/integration_tests/data/sql/data_generate_surrogate_key.csv', "[Errno 2] No such file or directory: 'dbt_packages/dbt_utils/integration_tests/data/sql/data_generate_surrogate_key.csv'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/data/sql/data_get_column_values.csv', 'dbt_packages/dbt_utils/integration_tests/data/sql/data_get_column_values.csv', "[Errno 2] No such file or directory: 'dbt_packages/dbt_utils/integration_tests/data/sql/data_get_column_values.csv'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/data/sql/data_get_column_values_dropped.csv', 'dbt_packages/dbt_utils/integration_tests/data/sql/data_get_column_values_dropped.csv', "[Errno 2] No such file or directory: 'dbt_packages/dbt_utils/integration_tests/data/sql/data_get_column_values_dropped.csv'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/data/sql/data_get_column_values_where.csv', 'dbt_packages/dbt_utils/integration_tests/data/sql/data_get_column_values_where.csv', "[Errno 2] No such file or directory: 'dbt_packages/dbt_utils/integration_tests/data/sql/data_get_column_values_where.csv'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/data/sql/data_get_column_values_where_expected.csv', 'dbt_packages/dbt_utils/integration_tests/data/sql/data_get_column_values_where_expected.csv', "[Errno 2] No such file or directory: 'dbt_packages/dbt_utils/integration_tests/data/sql/data_get_column_values_where_expected.csv'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/data/sql/data_get_query_results_as_dict.csv', 'dbt_packages/dbt_utils/integration_tests/data/sql/data_get_query_results_as_dict.csv', "[Errno 2] No such file or directory: 'dbt_packages/dbt_utils/integration_tests/data/sql/data_get_query_results_as_dict.csv'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/data/sql/data_get_single_value.csv', 'dbt_packages/dbt_utils/integration_tests/data/sql/data_get_single_value.csv', "[Errno 2] No such file or directory: 'dbt_packages/dbt_utils/integration_tests/data/sql/data_get_single_value.csv'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/data/sql/data_nullcheck_table.csv', 'dbt_packages/dbt_utils/integration_tests/data/sql/data_nullcheck_table.csv', "[Errno 2] No such file or directory: 'dbt_packages/dbt_utils/integration_tests/data/sql/data_nullcheck_table.csv'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/data/sql/data_pivot.csv', 'dbt_packages/dbt_utils/integration_tests/data/sql/data_pivot.csv', "[Errno 2] No such file or directory: 'dbt_packages/dbt_utils/integration_tests/data/sql/data_pivot.csv'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/data/sql/data_pivot_expected.csv', 'dbt_packages/dbt_utils/integration_tests/data/sql/data_pivot_expected.csv', "[Errno 2] No such file or directory: 'dbt_packages/dbt_utils/integration_tests/data/sql/data_pivot_expected.csv'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/data/sql/data_pivot_expected_apostrophe.csv', 'dbt_packages/dbt_utils/integration_tests/data/sql/data_pivot_expected_apostrophe.csv', "[Errno 2] No such file or directory: 'dbt_packages/dbt_utils/integration_tests/data/sql/data_pivot_expected_apostrophe.csv'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/data/sql/data_safe_add.csv', 'dbt_packages/dbt_utils/integration_tests/data/sql/data_safe_add.csv', "[Errno 2] No such file or directory: 'dbt_packages/dbt_utils/integration_tests/data/sql/data_safe_add.csv'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/data/sql/data_safe_divide.csv', 'dbt_packages/dbt_utils/integration_tests/data/sql/data_safe_divide.csv', "[Errno 2] No such file or directory: 'dbt_packages/dbt_utils/integration_tests/data/sql/data_safe_divide.csv'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/data/sql/data_safe_divide_denominator_expressions.csv', 'dbt_packages/dbt_utils/integration_tests/data/sql/data_safe_divide_denominator_expressions.csv', "[Errno 2] No such file or directory: 'dbt_packages/dbt_utils/integration_tests/data/sql/data_safe_divide_denominator_expressions.csv'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/data/sql/data_safe_divide_numerator_expressions.csv', 'dbt_packages/dbt_utils/integration_tests/data/sql/data_safe_divide_numerator_expressions.csv', "[Errno 2] No such file or directory: 'dbt_packages/dbt_utils/integration_tests/data/sql/data_safe_divide_numerator_expressions.csv'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/data/sql/data_safe_subtract.csv', 'dbt_packages/dbt_utils/integration_tests/data/sql/data_safe_subtract.csv', "[Errno 2] No such file or directory: 'dbt_packages/dbt_utils/integration_tests/data/sql/data_safe_subtract.csv'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/data/sql/data_star.csv', 'dbt_packages/dbt_utils/integration_tests/data/sql/data_star.csv', "[Errno 2] No such file or directory: 'dbt_packages/dbt_utils/integration_tests/data/sql/data_star.csv'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/data/sql/data_star_aggregate.csv', 'dbt_packages/dbt_utils/integration_tests/data/sql/data_star_aggregate.csv', "[Errno 2] No such file or directory: 'dbt_packages/dbt_utils/integration_tests/data/sql/data_star_aggregate.csv'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/data/sql/data_star_aggregate_expected.csv', 'dbt_packages/dbt_utils/integration_tests/data/sql/data_star_aggregate_expected.csv', "[Errno 2] No such file or directory: 'dbt_packages/dbt_utils/integration_tests/data/sql/data_star_aggregate_expected.csv'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/data/sql/data_star_expected.csv', 'dbt_packages/dbt_utils/integration_tests/data/sql/data_star_expected.csv', "[Errno 2] No such file or directory: 'dbt_packages/dbt_utils/integration_tests/data/sql/data_star_expected.csv'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/data/sql/data_star_prefix_suffix_expected.csv', 'dbt_packages/dbt_utils/integration_tests/data/sql/data_star_prefix_suffix_expected.csv', "[Errno 2] No such file or directory: 'dbt_packages/dbt_utils/integration_tests/data/sql/data_star_prefix_suffix_expected.csv'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/data/sql/data_star_quote_identifiers.csv', 'dbt_packages/dbt_utils/integration_tests/data/sql/data_star_quote_identifiers.csv', "[Errno 2] No such file or directory: 'dbt_packages/dbt_utils/integration_tests/data/sql/data_star_quote_identifiers.csv'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/data/sql/data_union_events_expected.csv', 'dbt_packages/dbt_utils/integration_tests/data/sql/data_union_events_expected.csv', "[Errno 2] No such file or directory: 'dbt_packages/dbt_utils/integration_tests/data/sql/data_union_events_expected.csv'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/data/sql/data_union_exclude_expected.csv', 'dbt_packages/dbt_utils/integration_tests/data/sql/data_union_exclude_expected.csv', "[Errno 2] No such file or directory: 'dbt_packages/dbt_utils/integration_tests/data/sql/data_union_exclude_expected.csv'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/data/sql/data_union_expected.csv', 'dbt_packages/dbt_utils/integration_tests/data/sql/data_union_expected.csv', "[Errno 2] No such file or directory: 'dbt_packages/dbt_utils/integration_tests/data/sql/data_union_expected.csv'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/data/sql/data_union_table_1.csv', 'dbt_packages/dbt_utils/integration_tests/data/sql/data_union_table_1.csv', "[Errno 2] No such file or directory: 'dbt_packages/dbt_utils/integration_tests/data/sql/data_union_table_1.csv'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/data/sql/data_union_table_2.csv', 'dbt_packages/dbt_utils/integration_tests/data/sql/data_union_table_2.csv', "[Errno 2] No such file or directory: 'dbt_packages/dbt_utils/integration_tests/data/sql/data_union_table_2.csv'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/data/sql/data_unpivot.csv', 'dbt_packages/dbt_utils/integration_tests/data/sql/data_unpivot.csv', "[Errno 2] No such file or directory: 'dbt_packages/dbt_utils/integration_tests/data/sql/data_unpivot.csv'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/data/sql/data_unpivot_bool.csv', 'dbt_packages/dbt_utils/integration_tests/data/sql/data_unpivot_bool.csv', "[Errno 2] No such file or directory: 'dbt_packages/dbt_utils/integration_tests/data/sql/data_unpivot_bool.csv'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/data/sql/data_unpivot_bool_expected.csv', 'dbt_packages/dbt_utils/integration_tests/data/sql/data_unpivot_bool_expected.csv', "[Errno 2] No such file or directory: 'dbt_packages/dbt_utils/integration_tests/data/sql/data_unpivot_bool_expected.csv'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/data/sql/data_unpivot_expected.csv', 'dbt_packages/dbt_utils/integration_tests/data/sql/data_unpivot_expected.csv', "[Errno 2] No such file or directory: 'dbt_packages/dbt_utils/integration_tests/data/sql/data_unpivot_expected.csv'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/data/sql/data_unpivot_original_api_expected.csv', 'dbt_packages/dbt_utils/integration_tests/data/sql/data_unpivot_original_api_expected.csv', "[Errno 2] No such file or directory: 'dbt_packages/dbt_utils/integration_tests/data/sql/data_unpivot_original_api_expected.csv'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/data/sql/data_unpivot_quote.csv', 'dbt_packages/dbt_utils/integration_tests/data/sql/data_unpivot_quote.csv', "[Errno 2] No such file or directory: 'dbt_packages/dbt_utils/integration_tests/data/sql/data_unpivot_quote.csv'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/data/sql/data_unpivot_quote_expected.csv', 'dbt_packages/dbt_utils/integration_tests/data/sql/data_unpivot_quote_expected.csv', "[Errno 2] No such file or directory: 'dbt_packages/dbt_utils/integration_tests/data/sql/data_unpivot_quote_expected.csv'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/data/sql/data_width_bucket.csv', 'dbt_packages/dbt_utils/integration_tests/data/sql/data_width_bucket.csv', "[Errno 2] No such file or directory: 'dbt_packages/dbt_utils/integration_tests/data/sql/data_width_bucket.csv'"), (<DirEntry 'sql'>, 'dbt_packages/dbt_utils/integration_tests/data/sql', '[Errno 2] No such file or directory'), ('dbt_packages/dbt-utils-1.3.0/integration_tests/data/web/data_urls.csv', 'dbt_packages/dbt_utils/integration_tests/data/web/data_urls.csv', "[Errno 2] No such file or directory: 'dbt_packages/dbt-utils-1.3.0/integration_tests/data/web/data_urls.csv'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/data/web/data_url_host.csv', 'dbt_packages/dbt_utils/integration_tests/data/web/data_url_host.csv', "[Errno 2] No such file or directory: 'dbt_packages/dbt-utils-1.3.0/integration_tests/data/web/data_url_host.csv'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/data/web/data_url_path.csv', 'dbt_packages/dbt_utils/integration_tests/data/web/data_url_path.csv', "[Errno 2] No such file or directory: 'dbt_packages/dbt-utils-1.3.0/integration_tests/data/web/data_url_path.csv'"), (<DirEntry 'web'>, 'dbt_packages/dbt_utils/integration_tests/data/web', "[Errno 2] No such file or directory: 'dbt_packages/dbt-utils-1.3.0/integration_tests/data/web'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/dbt_project.yml', 'dbt_packages/dbt_utils/integration_tests/dbt_project.yml', "[Errno 2] No such file or directory: 'dbt_packages/dbt-utils-1.3.0/integration_tests/dbt_project.yml'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/macros', 'dbt_packages/dbt_utils/integration_tests/macros', "[Errno 2] No such file or directory: 'dbt_packages/dbt-utils-1.3.0/integration_tests/macros'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/models', 'dbt_packages/dbt_utils/integration_tests/models', "[Errno 2] No such file or directory: 'dbt_packages/dbt-utils-1.3.0/integration_tests/models'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/package-lock.yml', 'dbt_packages/dbt_utils/integration_tests/package-lock.yml', "[Errno 2] No such file or directory: 'dbt_packages/dbt-utils-1.3.0/integration_tests/package-lock.yml'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/packages.yml', 'dbt_packages/dbt_utils/integration_tests/packages.yml', "[Errno 2] No such file or directory: 'dbt_packages/dbt-utils-1.3.0/integration_tests/packages.yml'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/profiles.yml', 'dbt_packages/dbt_utils/integration_tests/profiles.yml', "[Errno 2] No such file or directory: 'dbt_packages/dbt-utils-1.3.0/integration_tests/profiles.yml'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/README.md', 'dbt_packages/dbt_utils/integration_tests/README.md', "[Errno 2] No such file or directory: 'dbt_packages/dbt-utils-1.3.0/integration_tests/README.md'"), ('dbt_packages/dbt-utils-1.3.0/integration_tests/tests', 'dbt_packages/dbt_utils/integration_tests/tests', "[Errno 2] No such file or directory: 'dbt_packages/dbt-utils-1.3.0/integration_tests/tests'"), ('dbt_packages/dbt-utils-1.3.0/LICENSE', 'dbt_packages/dbt_utils/LICENSE', "[Errno 2] No such file or directory: 'dbt_packages/dbt-utils-1.3.0/LICENSE'"), ('dbt_packages/dbt-utils-1.3.0/macros', 'dbt_packages/dbt_utils/macros', "[Errno 2] No such file or directory: 'dbt_packages/dbt-utils-1.3.0/macros'"), ('dbt_packages/dbt-utils-1.3.0/Makefile', 'dbt_packages/dbt_utils/Makefile', "[Errno 2] No such file or directory: 'dbt_packages/dbt-utils-1.3.0/Makefile'"), ('dbt_packages/dbt-utils-1.3.0/pytest.ini', 'dbt_packages/dbt_utils/pytest.ini', "[Errno 2] No such file or directory: 'dbt_packages/dbt-utils-1.3.0/pytest.ini'"), ('dbt_packages/dbt-utils-1.3.0/README.md', 'dbt_packages/dbt_utils/README.md', "[Errno 2] No such file or directory: 'dbt_packages/dbt-utils-1.3.0/README.md'"), ('dbt_packages/dbt-utils-1.3.0/RELEASE.md', 'dbt_packages/dbt_utils/RELEASE.md', "[Errno 2] No such file or directory: 'dbt_packages/dbt-utils-1.3.0/RELEASE.md'"), ('dbt_packages/dbt-utils-1.3.0/run_functional_test.sh', 'dbt_packages/dbt_utils/run_functional_test.sh', "[Errno 2] No such file or directory: 'dbt_packages/dbt-utils-1.3.0/run_functional_test.sh'"), ('dbt_packages/dbt-utils-1.3.0/run_test.sh', 'dbt_packages/dbt_utils/run_test.sh', "[Errno 2] No such file or directory: 'dbt_packages/dbt-utils-1.3.0/run_test.sh'"), ('dbt_packages/dbt-utils-1.3.0/supported_adapters.env', 'dbt_packages/dbt_utils/supported_adapters.env', "[Errno 2] No such file or directory: 'dbt_packages/dbt-utils-1.3.0/supported_adapters.env'"), ('dbt_packages/dbt-utils-1.3.0/tox.ini', 'dbt_packages/dbt_utils/tox.ini', "[Errno 2] No such file or directory: 'dbt_packages/dbt-utils-1.3.0/tox.ini'")]
[2025-09-21T23:21:56.731+0000] {subprocess.py:106} INFO - 
[2025-09-21T23:21:57.734+0000] {subprocess.py:110} INFO - Command exited with return code 2
[2025-09-21T23:21:58.047+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-09-21T23:21:58.052+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-09-21T23:21:58.052+0000] {logging_mixin.py:190} INFO - Task start:2025-09-21 23:21:20.315703+00:00 end:2025-09-21 23:21:58.051598+00:00 duration:37.735895
[2025-09-21T23:21:58.053+0000] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): installing_required_dependencies> dag:<DAG: nawy_real_estate_pipeline> dagrun:<DagRun nawy_real_estate_pipeline @ 2025-09-20 05:27:01.289552+00:00: manual__2025-09-20T05:27:01.289552+00:00, state:running, queued_at: 2025-09-21 23:03:47.690964+00:00. externally triggered: True>
[2025-09-21T23:21:58.054+0000] {logging_mixin.py:190} INFO - Failure caused by Bash command failed. The command returned a non-zero exit code 2.
[2025-09-21T23:21:58.055+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=nawy_real_estate_pipeline, task_id=installing_required_dependencies, run_id=manual__2025-09-20T05:27:01.289552+00:00, execution_date=20250920T052701, start_date=20250921T232120, end_date=20250921T232158
[2025-09-21T23:21:58.388+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-09-21T23:21:58.389+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 362 for task installing_required_dependencies (Bash command failed. The command returned a non-zero exit code 2.; 313)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-09-21T23:21:58.423+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-09-21T23:21:58.464+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-21T23:21:58.815+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
